"use client";

import Image from "next/image";
import type { CSSProperties } from "react";

/**
 * How a ZISUN photograph is presented, everywhere.
 *
 * The photographs arrive as they are taken: a garden, a hotel corridor, a
 * street, different light, different distance. Shown raw they read as a
 * camera roll rather than a collection - and the two things doing most of
 * that damage were not the pictures themselves.
 *
 * 1. Every photograph faded in from the SAME grey pixel, so each one
 *    announced itself as a file being loaded.
 * 2. Every photograph sat on the SAME flat pink, so nothing tied a picture
 *    to the page it was on.
 *
 * Both are fixed from the photograph itself, with no work per picture and
 * nothing stored. The same image is requested at 64px - a ~2KB variant
 * next/image already generates - and painted behind the frame, scaled and
 * softened. A 64px image blown up IS its own colour field: the garden gives
 * a green ground, the wine set a burgundy one. The photograph then sits in a
 * setting drawn out of itself, which is the whole difference between a
 * picture pasted onto a page and a picture placed on one.
 *
 * The field sits BEHIND the photograph, not around it. Tried as a visible
 * mat at card size it read as a coloured halo - an artifact rather than a
 * frame - so it earns its place only as the loading state: it arrives first
 * because it is 2KB, so the space is never empty and never grey, and the
 * photograph resolves out of its own colours and then covers it completely.
 * Nothing moves, because the ratio is fixed.
 *
 * `focus` is where the subject is. Fashion photographs are full-length and
 * the face sits high, so a centre crop takes the head off; the default reads
 * the upper third. It is a prop rather than a guess per call site so that one
 * unusual picture can be corrected without touching the system.
 */
export interface PhotoProps {
  src: string;
  alt: string;
  /** Tailwind aspect class. Portrait by default - these are full-length. */
  ratio?: string;
  /**
   * Fill a parent that already has a size, instead of setting a ratio here.
   * The gallery needs this: `DepthPhoto` is `absolute inset-0` and collapses
   * to nothing unless its parent is sized, which is exactly what happened
   * when the ratio moved in here and the main photograph disappeared.
   */
  fill?: boolean;
  /** object-position. Default favours the upper body. */
  focus?: string | null;
  sizes: string;
  priority?: boolean;
  className?: string;
  /** Off for thumbnails, where a colour field is noise at 48px. */
  ground?: boolean;
  /** Scales on hover. Cards do; a gallery being swiped does not. */
  hover?: boolean;
  children?: React.ReactNode;
  style?: CSSProperties;
  vtName?: string;
}

/**
 * The founder's stored pair, as CSS. "50 28" means 50% across, 28% down -
 * percentages so it holds at every crop ratio. A value that already carries
 * a unit passes through, and nothing stored reads the upper third, which is
 * right for a full-length photograph.
 */
export function objectPositionFor(focus?: string | null): string {
  const f = (focus ?? "").trim();
  if (!f) return "50% 28%";
  if (/[%a-z]/i.test(f)) return f;
  const [x, y] = f.split(/\s+/);
  return x && y ? `${x}% ${y}%` : "50% 28%";
}

/** The tiny variant used as the colour field. Already generated by next/image. */
function groundSrc(src: string): string | null {
  if (!src || src.startsWith("data:") || src.endsWith(".svg")) return null;
  return src;
}

export function Photo({
  src,
  alt,
  ratio = "aspect-[3/4]",
  fill = false,
  focus,
  sizes,
  priority = false,
  className = "",
  ground = true,
  hover = false,
  children,
  style,
  vtName,
}: PhotoProps) {
  const field = ground ? groundSrc(src) : null;

  return (
    <div
      data-vt-photo
      className={`${fill ? "absolute inset-0" : `relative w-full ${ratio}`} overflow-hidden rounded-card bg-porcelain ${className}`}
      style={{ ...style, ...(vtName ? { viewTransitionName: vtName } : {}) }}
    >
      {/* The colour field, from the photograph itself. Scaled past the edges
          so no seam shows, and held still - it must never compete with the
          picture. aria-hidden: it carries no information. */}
      {field && (
        <Image
          src={field}
          alt=""
          aria-hidden
          fill
          sizes="64px"
          quality={40}
          priority={priority}
          className="scale-125 object-cover blur-2xl saturate-125 select-none"
        />
      )}

      {/* The photograph, filling the frame. */}
      <Image
        src={src}
        alt={alt}
        fill
        sizes={sizes}
        priority={priority}
        style={{ objectPosition: objectPositionFor(focus) }}
        className={`object-cover ${hover ? "transition-transform duration-500 ease-out group-hover:scale-[1.04]" : ""}`}
      />

      {/* A hairline, drawn inside. A photograph on a pale ground needs an
          edge or it bleeds into the page. Inset so it never adds a pixel to
          the layout, and faint enough to be felt rather than seen. */}
      <div className="pointer-events-none absolute inset-0 rounded-card ring-1 ring-inset ring-ink/[0.06]" aria-hidden />

      {children}
    </div>
  );
}
